version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/tools
    binary: tools
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'

# Docker configuration
dockers:
  - image_templates:
      - "ghcr.io/fgeck/tools:{{ .Version }}"
      - "ghcr.io/fgeck/tools:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/fgeck/tools:{{ .Major }}"
      - "ghcr.io/fgeck/tools:latest"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    skip_push: auto

# Homebrew cask (brews is deprecated)
homebrew_casks:
  - name: tools
    repository:
      owner: fgeck
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"

    directory: Casks

    homepage: "https://github.com/fgeck/tools"
    description: "A bookmark manager for your terminal commands"

    url:
      verified: github.com/fgeck/tools

    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tools"]
          end

    skip_upload: auto
