version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/tools
    binary: tools
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'

brews:
  - name: tools
    # You need to create a repository: github.com/fgeck/homebrew-tools
    repository:
      owner: fgeck
      name: homebrew-tools
      token: "{{ .Env.GITHUB_TOKEN }}"

    # Folder inside the repository
    folder: Formula

    homepage: "https://github.com/fgeck/tools"
    description: "A bookmark manager for your terminal commands"
    license: "MIT"

    # Install script
    install: |
      bin.install "tools"

    # Test the installation
    test: |
      system "#{bin}/tools", "--help"
